(function exposeStage1Config(root) {
  function deepFreeze(value) {
    if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
    Object.freeze(value);
    for (const child of Object.values(value)) deepFreeze(child);
    return value;
  }

  const config = {
    version: "v10.3",
    mode: "stage1_vertical_slice_0_6",
    run: {
      formalDuration: 900,
      verticalSliceEnd: 360,
      maxWeaponLevel: 7,
      maxPassiveLevel: 5,
      activeWeaponSlots: 6,
      passiveSlots: 6,
      playerIFrame: 0.6,
      spawnInterval: 0.82,
    },
    activeWeaponKeys: ["coin", "you", "suisui", "blood"],
    sprites: {
      tufei: {
        src: "assets/pixel-prototypes/bandit-v1-128.png",
        frames: 1,
        fps: 1,
        drawSize: 56,
      },
      yaoren: {
        src: "assets/enemy-rebuild-v1/yaoren-v1-sheet.png",
        frames: 4,
        fps: 6,
        drawSize: 60,
      },
      xiesui: {
        src: "assets/enemy-rebuild-v1/splitface-xiesui-v1-sheet.png",
        frames: 4,
        fps: 5,
        drawSize: 68,
      },
      wumian: {
        src: "assets/enemy-rebuild-v1/wandering-soul-v1-sheet.png",
        frames: 4,
        fps: 6,
        drawSize: 62,
      },
    },
    enemies: {
      tufei: {
        id: "tufei",
        text: "土匪",
        role: "chaser",
        hp: 24,
        hpPerSecond: 0.06,
        damage: 8,
        speed: 88,
        speedPerSecond: 0.016,
        exp: 4,
        color: "#c9c0b2",
        size: 16,
      },
      yaoren: {
        id: "yaoren",
        text: "药人",
        role: "tank",
        hp: 54,
        hpPerSecond: 0.11,
        damage: 11,
        speed: 52,
        speedPerSecond: 0.01,
        exp: 7,
        color: "#a98b78",
        size: 18,
      },
      xiesui: {
        id: "xiesui",
        text: "裂面邪祟",
        role: "sway_pouncer",
        hp: 72,
        hpPerSecond: 0.13,
        damage: 13,
        speed: 58,
        speedPerSecond: 0.012,
        exp: 9,
        color: "#75886d",
        size: 19,
        pounceCooldown: [3.2, 4.8],
        pounceWindup: 0.42,
        pounceDuration: 0.32,
        pounceSpeed: 245,
      },
      wumian: {
        id: "wumian",
        text: "游魂",
        role: "drifter",
        hp: 42,
        hpPerSecond: 0.09,
        damage: 10,
        speed: 66,
        speedPerSecond: 0.012,
        exp: 8,
        color: "#b783d7",
        size: 17,
      },
    },
    phases: [
      {
        from: 0,
        to: 30,
        label: "荒村追兵",
        pool: ["tufei", "tufei", "tufei"],
        spawnMult: 1.25,
        batch: 1,
        softCap: 34,
      },
      {
        from: 30,
        to: 120,
        label: "土匪围村",
        pool: ["tufei", "tufei", "tufei", "wumian"],
        spawnMult: 1.45,
        batch: 1,
        softCap: 52,
      },
      {
        from: 120,
        to: 240,
        label: "药人压境",
        pool: ["tufei", "tufei", "yaoren", "yaoren"],
        spawnMult: 1.65,
        batch: 2,
        softCap: 76,
      },
      {
        from: 240,
        to: 300,
        label: "游魂过境",
        pool: ["tufei", "yaoren", "wumian", "wumian"],
        spawnMult: 1.82,
        batch: 2,
        softCap: 90,
      },
      {
        from: 300,
        to: 360,
        label: "四邪合围",
        pool: ["tufei", "yaoren", "xiesui", "wumian"],
        spawnMult: 2.0,
        batch: 3,
        softCap: 112,
      },
      {
        from: 360,
        to: Infinity,
        label: "黑太岁残躯",
        pool: ["tufei", "yaoren", "xiesui", "wumian"],
        spawnMult: 1.55,
        batch: 2,
        softCap: 96,
      },
    ],
    events: [
      { at: 8, type: "banditPursuit", count: 8, label: "开场追兵" },
      { at: 120, type: "banditCharge", rows: 2, perSide: 8, label: "土匪冲阵" },
      { at: 235, type: "message", text: "阴风排成了行。", label: "游魂预警" },
      { at: 240, type: "soulCrossing", rows: 4, perRow: 7, label: "游魂过境" },
      { at: 350, type: "message", text: "地底有什么东西正在翻身。", label: "精英预警" },
      { at: 360, type: "elite", kind: "blackTaisui", label: "黑太岁残躯" },
    ],
    eliteBlackTaisui: {
      id: "eliteBlackTaisui",
      text: "黑太岁残躯",
      hp: 1850,
      damage: 18,
      speed: 54,
      exp: 120,
      color: "#8b7357",
      size: 25,
      sweepCooldown: 4.6,
      sweepRadius: 175,
      sweepHalfAngle: 0.72,
      sweepDamage: 20,
      pounceCooldown: 6.2,
      pollutionCooldown: 5.4,
      pollutionRadius: 52,
      pollutionDuration: 5.5,
      pollutionDamagePerSecond: 7,
    },
    debugJumps: [110, 230, 350],
  };

  root.DAOGUI_STAGE1_V103_CONFIG = deepFreeze(config);
})(window);
