(function exposeStage1Config(root) {
  function deepFreeze(value) {
    if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
    Object.freeze(value);
    for (const child of Object.values(value)) deepFreeze(child);
    return value;
  }

  const config = {
    version: "v10.5",
    mode: "stage1_build_growth_0_10",
    run: {
      formalDuration: 900,
      verticalSliceEnd: 600,
      maxWeaponLevel: 7,
      maxPassiveLevel: 5,
      activeWeaponSlots: 6,
      passiveSlots: 6,
      playerIFrame: 0.55,
      spawnInterval: 0.78,
    },
    sacrifice: {
      minHp: 1,
      daqianluDrainPerSecond: 0.00067,
      skinBurstRatio: 0.01,
      eyeBurstRatio: 0.01,
      ultimateRatio: 0.12,
      maxCombinedDrainPerMinute: 0.12,
      ledgerInterval: 2,
    },
    map: {
      texture: "assets/pixel-prototypes/village-ground-v1-512.png",
      tileSize: 512,
      bounds: { minX: -1800, maxX: 1800, minY: -1300, maxY: 1300 },
      obstacles: [
        { id: "well-west", type: "circle", x: -270, y: -190, r: 58, label: "枯井" },
        { id: "altar-east", type: "circle", x: 430, y: 235, r: 66, label: "石坛" },
        { id: "grave-north", type: "circle", x: -540, y: 330, r: 46, label: "乱坟" },
        { id: "wall-north", type: "rect", x: 95, y: -340, w: 310, h: 48, label: "断墙" },
        { id: "wall-west", type: "rect", x: -520, y: -30, w: 250, h: 46, label: "断墙" },
        { id: "fence-east", type: "rect", x: 250, y: 65, w: 48, h: 245, label: "朽栅" },
        { id: "house-se", type: "rect", x: 900, y: 500, w: 180, h: 120, label: "破屋" },
        { id: "shrine-nw", type: "circle", x: -1200, y: -800, r: 72, label: "废祠" },
        { id: "wall-ne", type: "rect", x: 650, y: -900, w: 260, h: 44, label: "残壁" },
        { id: "grave-sw", type: "circle", x: -1500, y: 700, r: 52, label: "孤坟" },
        { id: "fence-sw", type: "rect", x: -800, y: -750, w: 44, h: 200, label: "烂栅" },
        { id: "cave-se", type: "circle", x: 1300, y: -500, r: 65, label: "窑洞" },
      ],
    },
    activeWeaponKeys: ["coin", "you", "suisui", "fire", "blood", "general", "ultimate"],
    weaponTrees: {
      coin: { evolveAt: 7, evolvedName: "铜钱悬剑" },
      suisui: { choiceAt: 5, evolvedName: "李岁" },
      blood: {},
      fire: { evolveAt: 7, evolvedName: "火袄蜒行" },
      general: { evolveAt: 7, evolvedName: "巴虺一瞥" },
    },
    sprites: {
      tufei: {
        src: "assets/pixel-prototypes/bandit-v1-128.png",
        frames: 1,
        fps: 1,
        drawSize: 56,
      },
      yaoren: {
        src: "assets/enemy-rebuild-v1/yaoren-v1-sheet.png",
        frames: 4,
        fps: 6,
        drawSize: 60,
      },
      xiesui: {
        src: "assets/enemy-rebuild-v1/splitface-xiesui-v1-sheet.png",
        frames: 4,
        fps: 5,
        drawSize: 68,
      },
      wumian: {
        src: "assets/enemy-rebuild-v1/wandering-soul-v1-sheet.png",
        frames: 4,
        fps: 6,
        drawSize: 62,
      },
    },
    enemies: {
      tufei: {
        id: "tufei",
        text: "土匪",
        role: "chaser",
        hp: 30,
        hpPerSecond: 0.075,
        damage: 10,
        speed: 88,
        speedPerSecond: 0.016,
        exp: 4,
        color: "#c9c0b2",
        size: 16,
      },
      yaoren: {
        id: "yaoren",
        text: "药人",
        role: "tank",
        hp: 70,
        hpPerSecond: 0.14,
        damage: 14,
        speed: 52,
        speedPerSecond: 0.01,
        exp: 7,
        color: "#a98b78",
        size: 18,
      },
      xiesui: {
        id: "xiesui",
        text: "裂面邪祟",
        role: "sway_pouncer",
        hp: 92,
        hpPerSecond: 0.17,
        damage: 17,
        speed: 58,
        speedPerSecond: 0.012,
        exp: 9,
        color: "#75886d",
        size: 19,
        pounceCooldown: [3.2, 4.8],
        pounceWindup: 0.42,
        pounceDuration: 0.32,
        pounceSpeed: 245,
      },
      wumian: {
        id: "wumian",
        text: "游魂",
        role: "drifter",
        hp: 56,
        hpPerSecond: 0.12,
        damage: 13,
        speed: 66,
        speedPerSecond: 0.012,
        exp: 8,
        color: "#b783d7",
        size: 17,
      },
    },
    phases: [
      {
        from: 0,
        to: 30,
        label: "荒村追兵",
        pool: ["tufei", "tufei", "tufei"],
        spawnMult: 1.35,
        batch: 1,
        softCap: 40,
      },
      {
        from: 30,
        to: 120,
        label: "土匪围村",
        pool: ["tufei", "tufei", "tufei", "wumian"],
        spawnMult: 1.55,
        batch: 1,
        softCap: 58,
      },
      {
        from: 120,
        to: 240,
        label: "药人压境",
        pool: ["tufei", "tufei", "yaoren", "yaoren"],
        spawnMult: 1.75,
        batch: 2,
        softCap: 84,
      },
      {
        from: 240,
        to: 300,
        label: "游魂过境",
        pool: ["tufei", "yaoren", "wumian", "wumian"],
        spawnMult: 1.95,
        batch: 2,
        softCap: 102,
      },
      {
        from: 300,
        to: 390,
        label: "腊月十八降临",
        pool: ["tufei", "yaoren", "xiesui", "wumian"],
        spawnMult: 2.15,
        batch: 3,
        softCap: 120,
      },
      {
        from: 390,
        to: 600,
        label: "人魈道人压境",
        pool: ["yaoren", "xiesui", "xiesui", "wumian"],
        spawnMult: 2.3,
        batch: 3,
        softCap: 128,
      },
      {
        from: 600,
        to: Infinity,
        label: "三花丹阳子",
        pool: ["yaoren", "xiesui", "wumian"],
        spawnMult: 2.45,
        batch: 3,
        softCap: 140,
      },
    ],
    events: [
      { at: 8, type: "banditPursuit", count: 8, label: "开场追兵" },
      { at: 120, type: "banditCharge", rows: 2, perSide: 8, label: "土匪冲阵" },
      { at: 145, type: "message", text: "炼丹炉的火焰映红了半边天。", label: "丹阳子预警" },
      { at: 150, type: "elite", kind: "danyangzi", label: "丹阳子" },
      { at: 235, type: "message", text: "阴风排成了行。", label: "游魂预警" },
      { at: 240, type: "soulCrossing", rows: 4, perRow: 7, label: "游魂过境" },
      { at: 295, type: "message", text: "远处传来了低沉的笑声。", label: "腊月十八预警" },
      { at: 300, type: "boss", kind: "layue", label: "腊月十八" },
      { at: 385, type: "message", text: "一尊灰白纸神在戏台上转过身来。", label: "喜神预警" },
      { at: 390, type: "elite", kind: "xishen", label: "喜神" },
      { at: 590, type: "message", text: "三颗头颅一齐狂笑，丹阳子再度降临。", label: "三花预警" },
      { at: 600, type: "boss", kind: "sanhua", label: "三花丹阳子" },
    ],
    eliteBlackTaisui: {
      id: "eliteBlackTaisui",
      text: "黑太岁邪祟",
      hp: 5200,
      damage: 22,
      speed: 54,
      exp: 120,
      color: "#8b7357",
      size: 34,
      sweepCooldown: 4.6,
      sweepRadius: 175,
      sweepHalfAngle: 0.72,
      sweepDamage: 26,
      pounceCooldown: 6.2,
      pollutionCooldown: 5.4,
      pollutionRadius: 52,
      pollutionDuration: 5.5,
      pollutionDamagePerSecond: 10,
    },
    eliteDanyangzi: {
      id: "eliteDanyangzi",
      text: "丹阳子",
      hp: 9000,
      damage: 24,
      speed: 50,
      exp: 220,
      color: "#9d765d",
      size: 32,
      fireCooldown: 4.5,
      bellCooldown: 5.0,
    },
    bossLayue: {
      id: "bossLayue",
      text: "腊月十八",
      hp: 13000,
      damage: 26,
      speed: 46,
      exp: 260,
      color: "#e7d7c5",
      size: 34,
      shadowCooldown: 5.8,
      shadowWindup: 1.0,
      shadowDamage: 30,
      laneCooldown: 4.4,
      laneDamage: 23,
    },
    eliteRenxiao: {
      id: "eliteRenxiao",
      text: "人魈道人",
      hp: 7800,
      damage: 22,
      speed: 58,
      exp: 180,
      color: "#9a8a6e",
      size: 30,
      dashCooldown: 5.2,
      dashSpeed: 300,
      symbolCooldown: 3.8,
      symbolCount: 3,
      symbolDamage: 18,
    },
    eliteXishen: {
      id: "eliteXishen",
      text: "喜神",
      hp: 10000,
      damage: 26,
      speed: 52,
      exp: 200,
      color: "#e8e2d4",
      size: 30,
      signCooldown: 4.0,
      signCount: 3,
      signRange: 700,
      signDamage: 22,
      threadCooldown: 5.5,
      threadLength: 640,
      threadDamage: 28,
      puppetCooldown: 8.0,
      puppetCount: 2,
      puppetDamage: 15,
    },
    bossDanyangzi: {
      id: "bossDanyangzi",
      text: "丹阳子",
      hp: 19000,
      damage: 28,
      speed: 42,
      exp: 420,
      color: "#9d765d",
      size: 34,
      phaseTwoAt: 0.5,
      fireCooldown: 4.2,
      bellCooldown: 5.6,
      wingSweepCooldown: 4.8,
      radialDamage: 30,
    },
    bossSanhua: {
      id: "bossSanhua",
      text: "三花丹阳子",
      hp: 24000,
      damage: 32,
      speed: 46,
      exp: 500,
      color: "#b85a30",
      size: 40,
      phaseTwoAt: 0.5,
      fireCooldown: 3.5,
      bellCooldown: 4.8,
      wingSweepCooldown: 4.0,
      radialDamage: 35,
    },
    debugJumps: [145, 295, 385, 590],
  };

  root.DAOGUI_STAGE1_V105_CONFIG = deepFreeze(config);
})(window);
