(function exposeStage1Config(root) {
  function deepFreeze(value) {
    if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
    Object.freeze(value);
    for (const child of Object.values(value)) deepFreeze(child);
    return value;
  }

  const config = {
    version: "v10.5",
    mode: "stage1_build_growth_0_10",
    run: {
      formalDuration: 900,
      verticalSliceEnd: 600,
      maxWeaponLevel: 7,
      maxPassiveLevel: 5,
      activeWeaponSlots: 6,
      passiveSlots: 6,
      playerIFrame: 0.55,
      spawnInterval: 0.78,
    },
    sacrifice: {
      minHp: 1,
      daqianluDrainPerSecond: 0.00067,
      skinBurstRatio: 0.01,
      eyeBurstRatio: 0.01,
      ultimateRatio: 0.12,
      maxCombinedDrainPerMinute: 0.12,
      ledgerInterval: 2,
    },
    map: {
      texture: "assets/pixel-prototypes/village-ground-v1-512.png",
      tileSize: 512,
      bounds: { minX: -900, maxX: 900, minY: -650, maxY: 650 },
      obstacles: [
        { id: "well-west", type: "circle", x: -270, y: -190, r: 58, label: "枯井" },
        { id: "altar-east", type: "circle", x: 430, y: 235, r: 66, label: "石坛" },
        { id: "grave-north", type: "circle", x: -540, y: 330, r: 46, label: "乱坟" },
        { id: "wall-north", type: "rect", x: 95, y: -340, w: 310, h: 48, label: "断墙" },
        { id: "wall-west", type: "rect", x: -520, y: -30, w: 250, h: 46, label: "断墙" },
        { id: "fence-east", type: "rect", x: 250, y: 65, w: 48, h: 245, label: "朽栅" },
      ],
    },
    activeWeaponKeys: ["coin", "you", "suisui", "fire", "blood", "general"],
    weaponTrees: {
      coin: { evolveAt: 7, evolvedName: "铜钱悬剑" },
      suisui: { choiceAt: 4, evolvedName: "李岁", finalAt: 7, finalName: "玄牝" },
      blood: {
        branchAt: 3,
        branches: {
          tooth: { name: "牙祭", evolvedName: "齿雨贯阵" },
          nail: { name: "甲祭", evolvedName: "十甲血轮" },
          finger: { name: "指祭", evolvedName: "裂指成林" },
        },
      },
      fire: { evolveAt: 7, evolvedName: "火袄蜒行" },
      general: { evolveAt: 7, evolvedName: "巴虺一瞥" },
    },
    sprites: {
      tufei: {
        src: "assets/pixel-prototypes/bandit-v1-128.png",
        frames: 1,
        fps: 1,
        drawSize: 56,
      },
      yaoren: {
        src: "assets/enemy-rebuild-v1/yaoren-v1-sheet.png",
        frames: 4,
        fps: 6,
        drawSize: 60,
      },
      xiesui: {
        src: "assets/enemy-rebuild-v1/splitface-xiesui-v1-sheet.png",
        frames: 4,
        fps: 5,
        drawSize: 68,
      },
      wumian: {
        src: "assets/enemy-rebuild-v1/wandering-soul-v1-sheet.png",
        frames: 4,
        fps: 6,
        drawSize: 62,
      },
    },
    enemies: {
      tufei: {
        id: "tufei",
        text: "土匪",
        role: "chaser",
        hp: 30,
        hpPerSecond: 0.075,
        damage: 10,
        speed: 88,
        speedPerSecond: 0.016,
        exp: 4,
        color: "#c9c0b2",
        size: 16,
      },
      yaoren: {
        id: "yaoren",
        text: "药人",
        role: "tank",
        hp: 70,
        hpPerSecond: 0.14,
        damage: 14,
        speed: 52,
        speedPerSecond: 0.01,
        exp: 7,
        color: "#a98b78",
        size: 18,
      },
      xiesui: {
        id: "xiesui",
        text: "裂面邪祟",
        role: "sway_pouncer",
        hp: 92,
        hpPerSecond: 0.17,
        damage: 17,
        speed: 58,
        speedPerSecond: 0.012,
        exp: 9,
        color: "#75886d",
        size: 19,
        pounceCooldown: [3.2, 4.8],
        pounceWindup: 0.42,
        pounceDuration: 0.32,
        pounceSpeed: 245,
      },
      wumian: {
        id: "wumian",
        text: "游魂",
        role: "drifter",
        hp: 56,
        hpPerSecond: 0.12,
        damage: 13,
        speed: 66,
        speedPerSecond: 0.012,
        exp: 8,
        color: "#b783d7",
        size: 17,
      },
    },
    phases: [
      {
        from: 0,
        to: 30,
        label: "荒村追兵",
        pool: ["tufei", "tufei", "tufei"],
        spawnMult: 1.35,
        batch: 1,
        softCap: 40,
      },
      {
        from: 30,
        to: 120,
        label: "土匪围村",
        pool: ["tufei", "tufei", "tufei", "wumian"],
        spawnMult: 1.55,
        batch: 1,
        softCap: 58,
      },
      {
        from: 120,
        to: 240,
        label: "药人压境",
        pool: ["tufei", "tufei", "yaoren", "yaoren"],
        spawnMult: 1.75,
        batch: 2,
        softCap: 84,
      },
      {
        from: 240,
        to: 300,
        label: "游魂过境",
        pool: ["tufei", "yaoren", "wumian", "wumian"],
        spawnMult: 1.95,
        batch: 2,
        softCap: 102,
      },
      {
        from: 300,
        to: 360,
        label: "四邪合围",
        pool: ["tufei", "yaoren", "xiesui", "wumian"],
        spawnMult: 2.15,
        batch: 3,
        softCap: 120,
      },
      {
        from: 360,
        to: 480,
        label: "残蜕后的围猎",
        pool: ["tufei", "yaoren", "xiesui", "wumian"],
        spawnMult: 2.3,
        batch: 3,
        softCap: 128,
      },
      {
        from: 480,
        to: 600,
        label: "喜神压境",
        pool: ["yaoren", "xiesui", "xiesui", "wumian", "wumian"],
        spawnMult: 2.45,
        batch: 3,
        softCap: 140,
      },
      {
        from: 600,
        to: Infinity,
        label: "丹阳子",
        pool: ["yaoren", "xiesui", "wumian"],
        spawnMult: 1.72,
        batch: 2,
        softCap: 108,
      },
    ],
    events: [
      { at: 8, type: "banditPursuit", count: 8, label: "开场追兵" },
      { at: 120, type: "banditCharge", rows: 2, perSide: 8, label: "土匪冲阵" },
      { at: 235, type: "message", text: "阴风排成了行。", label: "游魂预警" },
      { at: 240, type: "soulCrossing", rows: 4, perRow: 7, label: "游魂过境" },
      { at: 350, type: "message", text: "地底有什么东西正在翻身。", label: "精英预警" },
      { at: 360, type: "elite", kind: "blackTaisui", label: "黑太岁邪祟" },
      { at: 470, type: "message", text: "远处有两个女人同时回过了头。", label: "喜神预警" },
      { at: 480, type: "elite", kind: "xishen", label: "喜神" },
      { at: 590, type: "message", text: "炼丹炉里传来了三种笑声。", label: "丹阳子预警" },
      { at: 600, type: "boss", kind: "danyangzi", label: "丹阳子" },
    ],
    eliteBlackTaisui: {
      id: "eliteBlackTaisui",
      text: "黑太岁邪祟",
      hp: 5200,
      damage: 22,
      speed: 54,
      exp: 120,
      color: "#8b7357",
      size: 34,
      sweepCooldown: 4.6,
      sweepRadius: 175,
      sweepHalfAngle: 0.72,
      sweepDamage: 26,
      pounceCooldown: 6.2,
      pollutionCooldown: 5.4,
      pollutionRadius: 52,
      pollutionDuration: 5.5,
      pollutionDamagePerSecond: 10,
    },
    eliteXishen: {
      id: "eliteXishen",
      text: "喜神",
      hp: 7600,
      damage: 24,
      speed: 48,
      exp: 190,
      color: "#e7d7c5",
      size: 28,
      shadowCooldown: 5.8,
      shadowWindup: 1.0,
      shadowDamage: 30,
      laneCooldown: 4.4,
      laneDamage: 23,
    },
    bossDanyangzi: {
      id: "bossDanyangzi",
      text: "丹阳子",
      hp: 19000,
      damage: 28,
      speed: 42,
      exp: 420,
      color: "#9d765d",
      size: 34,
      phaseTwoAt: 0.5,
      fireCooldown: 4.2,
      bellCooldown: 5.6,
      wingSweepCooldown: 4.8,
      radialDamage: 30,
    },
    debugJumps: [350, 470, 590],
  };

  root.DAOGUI_STAGE1_V105_CONFIG = deepFreeze(config);
})(window);
